### ISSUE TITLE
Mutlilanguage not possible

### ISSUE THREAD

**Issue by alrik11es** [Kilte/pagination#4]
As you're using class constants to save data as "next" "previous"... an external use for this library is not possible if you're looking for pagination in multilanguage environments.

**Comment by Kilte** [comment]
What exactly do you mean?

Repeating tags like this?
```php
[
    6 => 'previous', 
    7 => 'previous',
    8 => 'previous',
    9 => 'previous',
]
```
Let me know, if you have a better solution, please. =)

Maybe you want to get translations support?  I'm against on this. You can translate tags as you want:
```php
foreach ($pages as $page => $tag) {
    echo sprintf('<a href="?page=%u">%s</a>', $page, translate($tag));
} 
```

**Comment by alrik11es** [comment]
I think I misunderstood how to use your class.
Could you provide better documentation examples?

**Comment by Kilte** [comment]
I think it is self-explanatory.  

As for the tags, they could be used in a translation file for example:

```php
<?php
use Kilte\Pagination\Pagination;

return [
    Pagination::TAG_FIRST => 'В начало',
    Pagination::TAG_LESS => 'Меньше',
    /* ... */
    Pagination::TAG_CURRENT => 'Я здесь',
    /* ... */
    Pagination::TAG_MORE => 'Больше',
    Pagination::TAG_LAST => 'В конец',
];

```

**Comment by alrik11es** [comment]
Don't worry I'm going to try this lib for my project if I think I can improve the docs I will send a pull request.
Thanks.
